---
title: "CIHR Data Import"
output: html_notebook
author: "Leonard"
---


################################################################################
Data: CIHR Grants and Awards 2001 - 2020
Source: https://open.canada.ca/data/en/dataset/49edb1d7-5cb4-4fa7-897c-515d1aad5da3
################################################################################




```{r}
library(dplyr)
library(haven)
```


```{r}
# store all csv file names
csv_files <- list.files("00.Data/CIHR", pattern = "*.csv")

# load csv files and merge them into one dataframe
cihr_data <- data.frame() 
setwd("00.Data/CIHR")

for (file in csv_files) {
  file_path <- file
  csv_data <- read.csv(file_path)
  cihr_data <- bind_rows(cihr_data, csv_data)
}
```



```{r}
# Data filtering/restructuring 
cihr <- cihr_data %>% 
  select(Abstract.Résumé, Key.Clé, Name.Nom, OrgNm, ProvinceEN, CountryEN,
         CompetitionYear.AnnéeDuConcours, FiscalYear.AnnéeFinancière,
         AwardAmountinFY.MontantSubventiondeAF, TotalAwardAmount.MontantSubventionTotal,
         ProgramIDProgramme, ProgramNameEN, FundingTypeEN, AreasOfScienceEN, ResearchClassEN,
         TitreApplicationTitle, Keywords.MotsClés) %>% 
  rename(abstract = Abstract.Résumé,
         key = Key.Clé,
         name = Name.Nom,
         organization = OrgNm,
         province = ProvinceEN,
         country = CountryEN,
         year_comp = CompetitionYear.AnnéeDuConcours, 
         year_fisc = FiscalYear.AnnéeFinancière, 
         programID = ProgramIDProgramme,
         program_name = ProgramNameEN,
         funding_type = FundingTypeEN,
         science_areas = AreasOfScienceEN,
         research_class = ResearchClassEN,
         title = TitreApplicationTitle,
         keywords = Keywords.MotsClés) %>%
  mutate(abstract = ifelse(nchar(abstract) <= 30, NA, abstract))



hist(cihr$year_comp)
```




