---
title: "CRSH_analyses"
author: "Julie, Firdaous et Rachel"
date: "2023-06-28"
output: pdf_document
---
Chargement des données
```{r}
library(readxl)
library(tidyverse)
CRSH_1998_2010 <- read_excel("00.Data/CRSH_1998-2010.xls")
CRSH_2011_2021 <- read_excel("00.Data/CRSH_2011-2021.xls")
```
Fusionner les rangées et renommer les colonnes
```{r}
colnames(CRSH_1998_2010)  <- CRSH_1998_2010[2, ]
colnames(CRSH_2011_2021)  <- CRSH_2011_2021[2, ]
CRSH1 <- CRSH_1998_2010[-c(1,2), ]
CRSH2 <- CRSH_2011_2021[-c(1,2), ]
CRSH_tot <- bind_rows(CRSH1, CRSH2)
colnames(CRSH_tot) <- c("Candidat", "Organisme", "Titre", "Montant", "Année", "Code")
```
Supprimer les demandes sans titre de projet
```{r}
CRSH_st <- CRSH_tot |> 
  filter(!Titre == "No Title - Aucun titre") |> 
  filter(!Titre == "No Title - Aucun Titre") |> 
  filter(!Titre == "No title - Aucun titre") |> 
  filter(!Titre == "No title")
```
Création de la variable Langue
```{r}
#install.packages("cld2")
#install.packages("cld3")
library(cld2)
library(cld3)
CRSH_st$Langue2 <- cld2::detect_language(CRSH_st$Titre)
CRSH_st$Langue3 <- cld3::detect_language(CRSH_st$Titre)

CRSH_lang <- CRSH_st |> 
  mutate(
    Langue = case_when(
      Langue2 == "en" & Langue3 == "fr" ~ "bi",
      Langue2 == "fr" & Langue3 == "en" ~ "bi",
      Langue2 == "en" ~ "angl",
      Langue2 == "fr" ~ "fran",
      is.na(Langue2) & Langue3 == "fr" ~ "fran",
      is.na(Langue2) & Langue3 == "en" ~ "angl"
    ))
```
Jeu de données final
```{r}
CRSH_final <- CRSH_lang[ , -c(7,8)]

```
# intégration de la colonne Concours dans la bd final
```{r}
CRSH_codes <- read_csv("CRSH_codes.csv")
CRSH_codes$Code <- as.character(CRSH_codes$Code)
CRSH3 <- left_join(CRSH_final, CRSH_codes, by = "Code")
```
# Création de la colonne Statut
```{r}
CRSH4 <- CRSH3 |> 
  mutate(Concours = str_to_lower(Concours),
         statut = if_else(str_detect(Concours, "student") == TRUE | 
                          str_detect(Concours, "master") == TRUE | 
                          str_detect(Concours, "doctoral") == TRUE | 
                          str_detect(Concours, "graduate") == TRUE | 
                          str_detect(Concours, "postdoctoral") == TRUE, "etudiant", "professeur"))
```


```{r}
```


```{r}
```




